# Generated by Django 2.2.5 on 2019-09-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('bookingID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('isAvailable', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('dayID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interestID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('timeSlotID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=30)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Deactive')])),
                ('password', models.TextField(max_length=255)),
                ('isTutor', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('isStudent', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Interests')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TutorBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Availability')),
                ('interestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Interests')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Users')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Availability')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Users')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='dayID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Days'),
        ),
        migrations.AddField(
            model_name='availability',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Rooms'),
        ),
        migrations.AddField(
            model_name='availability',
            name='timeSlotID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.TimeSlots'),
        ),
    ]
