# Generated by Django 2.2.5 on 2019-09-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='deptID',
        ),
    ]
