# Generated by Django 2.2.5 on 2019-09-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_remove_users_deptid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
